### ISSUE TITLE
BUG: The component "Form.jsx" rerenders multiple times.

### ISSUE THREAD

**Issue by Halim-Shams** [Halim-Shams/Awesome-todo#1]
If you look at the component `Form.jsx`, it renders multiple times, which will slow down the performance.

You can see this issue by having a look at the console, as the `console.log()` occurs several times and never ends.

**Comment by Mohit-3007** [comment]
Hi @Halim-Shams 
i would like to do the fix the bug, kindly assign me for the same.

**Comment by ankit2821** [comment]
Hi @Halim-Shams I would like to fix this bug, Can you assign me for the same.
